### ISSUE TITLE
Facebook share button not working

### ISSUE THREAD

**Issue by bebertz93** [pasupulaphani/angular-socialsharing#2]
Hi,

First, I want to say thanks for this great lib.
I got a problem with the facebook share button. When I first use it, it works fine but it suddenly stop working. Also, the facebook share button in the demo is not working. Can you help me with this?

Thanks!

**Comment by pasupulaphani** [comment]
Sure mate. Give me few mins

**Comment by bebertz93** [comment]
Thanks! By the way, I just tested it in mobile and there's no problem when using it in mobile. I think the problem is when using it in desktop.

**Comment by pasupulaphani** [comment]
Hi @albertonaperijr , The demo is working fine for me. I just asked my friend and it worked for him without any problems.

Please make sure that your Facebook app is set-up properly and is made available to public. (find it under "Status and Review" settings of your FB app)

**Comment by pasupulaphani** [comment]
We tested on desktop.

**Comment by bebertz93** [comment]
Thanks @pasupulaphani! Sorry about that. The problem was with the browser that I'm using. I've tested it with other browsers and it works just fine.

Thanks again for the time.

**Comment by pasupulaphani** [comment]
no worries.
